SHELL = cmd

BIN = Bin
SOURCE = Source
TEMP = Temp
TESTS = Tests

THREADCALLNAME = ThreadCall
TESTSNAME = Tests

THREADCALLDLL = $(BIN)/lib$(THREADCALLNAME).dll
TESTSEXE = $(BIN)/$(TESTSNAME).exe

All: $(THREADCALLDLL) $(TESTSEXE)
	$(TESTSEXE)

$(THREADCALLDLL) : $(SOURCE)/$(THREADCALLNAME).c
	gcc -c -fPIC $(SOURCE)/$(THREADCALLNAME).c -o $(TEMP)/$(THREADCALLNAME).o
	gcc -shared $(TEMP)/$(THREADCALLNAME).o -lpthread -o $(THREADCALLDLL)

$(TESTSEXE) : $(TESTS)/$(TESTSNAME).c
	gcc -c -I$(SOURCE) $(TESTS)/$(TESTSNAME).c -o $(TEMP)/$(TESTSNAME).o
	gcc -L$(BIN) $(TEMP)/$(TESTSNAME).o -l$(THREADCALLNAME) -lpthread -o $(TESTSEXE)

Clean:
	DEL /Q $(BIN)\*.dll $(BIN)\*.exe
	DEL /Q $(TEMP)\*.o